package com.nuntly.sdk.models;

public record Error(
    /** The HTTP status code generated by the origin server for this occurrence of the error. */
    long status,
    /** An API specific code representing the type of error. */
    String code,
    /** A short, human-readable summary of the error type. */
    String title,
    /** A (best effort) human readable explanation specific to this occurrence of the error. */
    java.util.Optional<java.util.Map<String, Object>> details) {}
