package com.nuntly.sdk.lib;

import com.google.gson.Gson;
import com.google.gson.JsonParser;
import com.nuntly.sdk.models.EmailBouncedEvent;
import com.nuntly.sdk.models.EmailClickedEvent;
import com.nuntly.sdk.models.EmailComplainedEvent;
import com.nuntly.sdk.models.EmailDeliveredEvent;
import com.nuntly.sdk.models.EmailDeliveryDelayedEvent;
import com.nuntly.sdk.models.EmailFailedEvent;
import com.nuntly.sdk.models.EmailOpenedEvent;
import com.nuntly.sdk.models.EmailProcessedEvent;
import com.nuntly.sdk.models.EmailQueuedEvent;
import com.nuntly.sdk.models.EmailRejectedEvent;
import com.nuntly.sdk.models.EmailScheduledEvent;
import com.nuntly.sdk.models.EmailSendingEvent;
import com.nuntly.sdk.models.EmailSentEvent;
import com.nuntly.sdk.models.MessageAgentTriggeredEvent;
import com.nuntly.sdk.models.MessageReceivedEvent;
import com.nuntly.sdk.models.MessageRejectedEvent;
import com.nuntly.sdk.models.MessageSecurityFlaggedEvent;
import com.nuntly.sdk.models.MessageSentEvent;
import com.nuntly.sdk.models.UnknownWebhookEvent;
import com.nuntly.sdk.models.WebhookEvent;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.Arrays;
import java.util.HexFormat;
import java.util.Map;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

/**
 * Verify the signature of an incoming Nuntly webhook and decode the typed event.
 *
 * <p>The signature header has the form:
 *
 * <pre>{@code
 * t=<unix-seconds>,v0=<hex-signature>[,v0=<additional-hex-signatures>]
 * }</pre>
 *
 * <p>The signing secret may be passed with or without the {@code whsec_} prefix.
 *
 * <p>The returned {@link WebhookEvent} is a sealed type. Pattern-match on the concrete subtype to
 * handle each event, with {@link UnknownWebhookEvent} as a forward-compatible fallback for event
 * types this SDK version does not yet model:
 *
 * <pre>{@code
 * var event = Webhook.verify(payload, signatureHeader, secret);
 * switch (event) {
 *   case EmailBouncedEvent e -> handleBounce(e);
 *   case MessageReceivedEvent e -> handleReceive(e);
 *   case UnknownWebhookEvent e -> log.warn("unknown event type: {}", e.type());
 *   default -> log.warn("unhandled event type: {}", event.type());
 * }
 * }</pre>
 */
public final class Webhook {
  private static final Duration DEFAULT_TOLERANCE = Duration.ofMinutes(5);
  private static final String SECRET_PREFIX = "whsec_";
  private static final Gson GSON = new Gson();

  // Maps each Nuntly event type wire value (e.g. "email.delivered") to the
  // concrete record class generated by the SDK. Keep this in sync with the
  // `permits` clause of WebhookEvent and with WEBHOOK_EVENT_RECORDS in
  // sdks/generator/src/java-generator.ts.
  private static final Map<String, Class<? extends WebhookEvent>> EVENT_RECORD_BY_TYPE =
      Map.ofEntries(
          Map.entry("email.queued", EmailQueuedEvent.class),
          Map.entry("email.scheduled", EmailScheduledEvent.class),
          Map.entry("email.processed", EmailProcessedEvent.class),
          Map.entry("email.sending", EmailSendingEvent.class),
          Map.entry("email.sent", EmailSentEvent.class),
          Map.entry("email.delivered", EmailDeliveredEvent.class),
          Map.entry("email.opened", EmailOpenedEvent.class),
          Map.entry("email.clicked", EmailClickedEvent.class),
          Map.entry("email.bounced", EmailBouncedEvent.class),
          Map.entry("email.complained", EmailComplainedEvent.class),
          Map.entry("email.rejected", EmailRejectedEvent.class),
          Map.entry("email.deliveryDelayed", EmailDeliveryDelayedEvent.class),
          Map.entry("email.failed", EmailFailedEvent.class),
          Map.entry("message.received", MessageReceivedEvent.class),
          Map.entry("message.security.flagged", MessageSecurityFlaggedEvent.class),
          Map.entry("message.agent.triggered", MessageAgentTriggeredEvent.class),
          Map.entry("message.sent", MessageSentEvent.class),
          Map.entry("message.rejected", MessageRejectedEvent.class));

  private Webhook() {}

  public static WebhookEvent verify(String payload, String signatureHeader, String secret) {
    return verify(payload, signatureHeader, secret, DEFAULT_TOLERANCE);
  }

  public static WebhookEvent verify(
      String payload, String signatureHeader, String secret, Duration tolerance) {
    if (signatureHeader == null || signatureHeader.isBlank()) {
      throw new WebhookVerificationError("Missing webhook signature header");
    }
    if (secret == null || secret.isBlank()) {
      throw new WebhookVerificationError("Missing webhook signing secret");
    }
    if (payload == null) {
      throw new WebhookVerificationError("Missing webhook payload");
    }

    var rawKey =
        secret.startsWith(SECRET_PREFIX) ? secret.substring(SECRET_PREFIX.length()) : secret;

    var parts = signatureHeader.split(",");
    if (parts.length < 2) {
      throw new WebhookVerificationError("Invalid signature header format");
    }
    var tsPart = parts[0];
    if (!tsPart.startsWith("t=")) {
      throw new WebhookVerificationError("Invalid signature header: missing timestamp");
    }
    long ts;
    try {
      ts = Long.parseLong(tsPart.substring(2));
    } catch (NumberFormatException e) {
      throw new WebhookVerificationError("Invalid timestamp");
    }
    var ageSeconds = (System.currentTimeMillis() / 1000L) - ts;
    if (ageSeconds > tolerance.toSeconds()) {
      throw new WebhookVerificationError("Webhook timestamp is too old");
    }

    var candidates =
        Arrays.stream(parts, 1, parts.length)
            .filter(s -> s.startsWith("v0="))
            .map(s -> s.substring(3))
            .toArray(String[]::new);
    if (candidates.length == 0) {
      throw new WebhookVerificationError("No v0 signature found in header");
    }

    var signedContent = ts + "." + payload;
    var expected = hmacSha256Hex(rawKey, signedContent);

    var matched = false;
    for (var sig : candidates) {
      if (timingSafeEquals(sig, expected)) {
        matched = true;
        break;
      }
    }
    if (!matched) {
      throw new WebhookVerificationError("Webhook signature verification failed");
    }

    return parseEvent(payload);
  }

  private static String hmacSha256Hex(String key, String data) {
    try {
      var mac = Mac.getInstance("HmacSHA256");
      mac.init(new SecretKeySpec(key.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
      var digest = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
      return HexFormat.of().formatHex(digest);
    } catch (Exception e) {
      throw new WebhookVerificationError("Failed to compute HMAC-SHA256: " + e.getMessage());
    }
  }

  private static boolean timingSafeEquals(String a, String b) {
    if (a.length() != b.length()) return false;
    return MessageDigest.isEqual(
        a.getBytes(StandardCharsets.UTF_8), b.getBytes(StandardCharsets.UTF_8));
  }

  private static WebhookEvent parseEvent(String payload) {
    var json = JsonParser.parseString(payload).getAsJsonObject();
    var type =
        json.has("type") && !json.get("type").isJsonNull() ? json.get("type").getAsString() : null;
    var recordClass = type != null ? EVENT_RECORD_BY_TYPE.get(type) : null;
    if (recordClass != null) {
      return GSON.fromJson(json, recordClass);
    }
    // Unknown event type: keep forward-compatibility by returning the raw shape.
    var id = json.has("id") && !json.get("id").isJsonNull() ? json.get("id").getAsString() : null;
    var createdAt =
        json.has("createdAt") && !json.get("createdAt").isJsonNull()
            ? json.get("createdAt").getAsString()
            : null;
    var data =
        json.has("data") && json.get("data").isJsonObject()
            ? json.get("data").getAsJsonObject()
            : new com.google.gson.JsonObject();
    return new UnknownWebhookEvent(id, createdAt, type, data);
  }
}
